name: test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test code
        run: yarn run test:unit
  # build:
  #   needs: test
  #   runs-on: ubuntu-latest
